---
- hosts: all
  become: true
  vars:
    doc_root: /home/{$USER}
  tasks:
    - name: Update apt
      apt: update_cache=yes

    - name: vscode
    - name: # The repository and key can also be installed manually with the following script:
curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg
sudo install -o root -g root -m 644 packages.microsoft.gpg /usr/share/keyrings/
sudo sh -c 'echo "deb [arch=amd64 signed-by=/usr/share/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list'

    - name: # First, update the packages index and install the dependencies by typing:

sudo apt update

sudo apt install software-properties-common apt-transport-https wget $OPTIONS

    - name: # Next, import the Microsoft GPG key using the following [wget command](https://linuxize.com/post/wget-command-examples/):

wget -q https://packages.microsoft.com/keys/microsoft.asc -O- | sudo apt-key add -

    - name: # And enable the Visual Studio Code repository by typing:

sudo add-apt-repository "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"

    - name: # Once the [apt repository is enabled](https://linuxize.com/post/how-to-add-apt-repository-in-ubuntu/), install the latest version of Visual Studio Code with:

