---
- hosts: all
  become: true
  vars:
    doc_root: /home/{$USER}
  tasks:
    - name: Update apt
      apt: update_cache=yes

    - name: docker-compose 
    - name: docker 
    - name: doctl 
    - name: # Update the apt package index and install packages to allow apt to use a repository over HTTPS:

sudo apt-get update

sudo apt-get install \
	apt-transport-https \
    ca-certificates \
    curl \
    gnupg \
    lsb-release

    - name: # Add Docker’s official GPG key:

curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

    - name: # Use the following command to set up the stable repository. To add the nightly or test repository, add the word nightly or test (or both) after the word stable in the commands below. Learn about nightly and test channels.

echo \
  "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian \
  $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

    - name: # Install Docker Engine

sudo apt-get update

sudo apt-get install docker-ce docker-ce-cli containerd.io

    - name: # Verify that Docker Engine is installed correctly by running the hello-world image as sudo

sudo docker run hello-world

    - name: # Manage Docker as a non-root user

    - name: # To create the docker group and add your user:

    - name: # Create the docker group.

newgrp docker 

sudo groupadd docker

    - name: # Add your user to the docker group.

sudo usermod -aG docker $USER

    - name: # Verify that you can run docker commands without sudo.

docker run hello-world
    - name: 
